name: 'tiktok_ads_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars: 
  tiktok_ads:

  #  change to data file names 

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']